FROM mcr.microsoft.com/playwright/python:v1.47.0-jammy
WORKDIR /home/python-sitemap/
COPY main.py crawler.py config.py /home/python-sitemap/
ENTRYPOINT [ "python", "main.py" ]
CMD [ "--domain", "http://blog.lesite.us", "--render-js" ]
